Comment out build and test steps in Intel Linux workflow due to unresolved issues with Intel oneAPI compilers

diff --git a/.github/workflows/ubuntu_intel.yaml b/.github/workflows/ubuntu_intel.yaml
--- a/.github/workflows/ubuntu_intel.yaml
+++ b/.github/workflows/ubuntu_intel.yaml
@@ -103,35 +103,36 @@ jobs:
             /opt/intel
           key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('nexus/ci/spack.yaml') }}
 
-      - name: build
-        run: |
-          source spack/share/spack/setup-env.sh
-          spack env activate nexus-env
-          export CC=mpiicx    # Intel oneAPI LLVM C compiler with MPI wrapper
-          export CXX=mpiicpx  # Intel oneAPI LLVM C++ compiler with MPI wrapper
-          export FC=mpiifort  # Intel Classic Fortran compiler with MPI wrapper (compatibility)
-          cd nexus
-          mkdir -p build && cd build
-          cmake -DCMAKE_INSTALL_PREFIX=../install ..
-          make -j2 VERBOSE=1
-          make install
+      # TODO: enable build and test steps once issues with Intel oneAPI compilers are resolved
+      # - name: build
+      #   run: |
+      #     source spack/share/spack/setup-env.sh
+      #     spack env activate nexus-env
+      #     export CC=mpiicx    # Intel oneAPI LLVM C compiler with MPI wrapper
+      #     export CXX=mpiicpx  # Intel oneAPI LLVM C++ compiler with MPI wrapper
+      #     export FC=mpiifort  # Intel Classic Fortran compiler with MPI wrapper (compatibility)
+      #     cd nexus
+      #     mkdir -p build && cd build
+      #     cmake -DCMAKE_INSTALL_PREFIX=../install ..
+      #     make -j2 VERBOSE=1
+      #     make install
 
-      - name: ctest
-        run: |
-          source spack/share/spack/setup-env.sh
-          spack env activate nexus-env
-          cd nexus
-          set -x
-          bin="$PWD/build/bin/nexus"
-          failed=0
-          cd tests/cases
-          for d in *; do
-            cd $d
-            $bin -c NEXUS_Config.rc -r grid_spec.nc || failed=1
-            if [[ "$failed" == 1 ]]; then
-              tail -n 20 NEXUS.log
-              cat PET0.ESMF_LogFile
-              exit 1
-            fi
-            cd ..
-          done
+      # - name: ctest
+      #   run: |
+      #     source spack/share/spack/setup-env.sh
+      #     spack env activate nexus-env
+      #     cd nexus
+      #     set -x
+      #     bin="$PWD/build/bin/nexus"
+      #     failed=0
+      #     cd tests/cases
+      #     for d in *; do
+      #       cd $d
+      #       $bin -c NEXUS_Config.rc -r grid_spec.nc || failed=1
+      #       if [[ "$failed" == 1 ]]; then
+      #         tail -n 20 NEXUS.log
+      #         cat PET0.ESMF_LogFile
+      #         exit 1
+      #       fi
+      #       cd ..
+      #     done
